### ISSUE TITLE
Version 0.2.3 does not build with Rust 1.0.0 beta

### ISSUE THREAD

**Issue by b52** [kevinmehall/rust-peg#77]
I'm unable to compile latest rust-peg 0.2.3 with the Rust 1.0.0 beta release for Windows x64.

**Used build tools:**
```
> cargo --version
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-04-01)

> rustc --version
rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)
```

**Build errors:**
```
D:\Users\amader\.cargo\git\checkouts\rust-peg-3bb581b77f5cbfba\master\src\rustast.rs:24:4: 24:31 error: type `syntax::ast::Path` does not implement any method in scope named `unwrap_or_else`
D:\Users\amader\.cargo\git\checkouts\rust-peg-3bb581b77f5cbfba\master\src\rustast.rs:24 	r.unwrap_or_else(|_|panic!())
                                                                                        	  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\Users\amader\.cargo\git\checkouts\rust-peg-3bb581b77f5cbfba\master\src\rustast.rs:36:4: 36:33 error: type `syntax::ptr::P<syntax::ast::Block>` does not implement any method in scope named `unwrap_or_else`
D:\Users\amader\.cargo\git\checkouts\rust-peg-3bb581b77f5cbfba\master\src\rustast.rs:36 	r.unwrap_or_else(|e| panic!(e))
                                                                                        	  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\Users\amader\.cargo\git\checkouts\rust-peg-3bb581b77f5cbfba\master\src\peg_syntax_ext.rs:97:49: 97:78 error: type `bool` does not implement any method in scope named `unwrap_or_else`
D:\Users\amader\.cargo\git\checkouts\rust-peg-3bb581b77f5cbfba\master\src\peg_syntax_ext.rs:97                     if !parser.eat(&token::Eof).unwrap_or_else(|e| panic!(e)) {
```

**Comment by kevinmehall** [comment]
This library requires the nightly version of Rust as syntax extensions are feature-gated in the beta and 1.0.

**Comment by kevinmehall** [comment]
Duplicate of #72
